### ISSUE TITLE
强烈推荐建议适配chrome书签json结构，方便一键导出生成

### ISSUE THREAD

**Issue by fulige18** [BahuangShanren/webstack-hugo#1]
如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。我觉得效率简直不要太高，门槛又低。
现有我发现的有2款书签导出插件：
一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url)
一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url)
。

**Comment by BahuangShanren** [comment]
1. 只是基于原作者的repo稍微改了一下，没什么可称道之处。
2. > 适配一下chrome书签的结构 

    你希望方便地将Chrome的书签导入到导航站里吗？或者是你觉得导航站里的站点值得收藏，想导出到你的Chrome书签里？
3. 导航站、书签栏、新建标签页以及插件，这四者间的转化或结合，玩法很多，但我暂时没有时间和兴趣在这方面继续。
4. 你发的两个链接很好，但都指向同一个repo，大概是贴错了。

**Comment by BahuangShanren** [comment]
明白你的需求了。
我觉得写一个单网页，通过`js`将Chrome导出的`html`格式书签转化为`yaml`，比修改本项目以适应`json`更合适一些（虽然`hugo`本身支持`json`），然而做了一会儿发现有点麻烦，另外`description`和`logo`还要后期手动处理，这还不如直接用其他有后台的二次开发实现呢🤦‍♂️
[WebStackPage/WebStackPage.github.io](https://github.com/WebStackPage/WebStackPage.github.io)推荐的二次开发实现：https://github.com/WebStackPage/WebStackPage.github.io#怎么用

**Comment by BahuangShanren** [comment]
抱歉，我目前不是很有时间和兴趣做这件事，也许以后会做？此贴终结。
